"""
Agent implementation using CrewAI.

Agents use CrewAI when available, with LiteLLM as a fallback for generation.
This keeps the public game API stable while moving agent execution to CrewAI.
"""

from typing import Dict, Optional, Any, TYPE_CHECKING
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
from enum import Enum
import asyncio
import contextlib
import io
import logging
import json
import os

logger = logging.getLogger(__name__)

for _proxy_var in ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"):
    os.environ.pop(_proxy_var, None)
os.environ.setdefault("LITELLM_LOCAL_MODEL_COST_MAP", "True")
os.environ.setdefault("CREWAI_DISABLE_TELEMETRY", "true")

try:
    from crewai import Agent as CrewAIAgent
    from crewai import LLM as CrewAILLM
except ImportError:
    CrewAIAgent = None
    CrewAILLM = None

from services.memory_service import AgentMemorySystem

if TYPE_CHECKING:
    from services.llm_service import LLMService
from config.settings import settings


class IQLevel(str, Enum):
    """Agent IQ level enumeration."""
    HIGH = "High"
    MID = "Mid"
    LOW = "Low"


class AgentRole(str, Enum):
    """Agent role in the game."""
    UNDERCOVER = "Undercover"
    CIVILIAN = "Civilian"


class AgentConfig(BaseModel):
    """Configuration for creating an agent."""
    id: str = Field(..., description="Unique agent identifier")
    mbti_type: str = Field(..., min_length=4, max_length=4, description="MBTI personality type")
    iq_level: IQLevel = Field(..., description="Agent's cognitive ability level")
    word: Optional[str] = Field(default=None, description="Word assigned to agent")
    role: AgentRole = Field(default=AgentRole.CIVILIAN, description="Agent's role")
    name: Optional[str] = Field(default=None, description="Display name generated by LLM")
    
    @field_validator('mbti_type')
    @classmethod
    def validate_mbti(cls, v: str) -> str:
        """Validate MBTI type format."""
        valid_types = {
            "ENTJ", "INFP", "ISTP", "ENFJ", "INTP",
            "ESTJ", "ISFP", "ENTP", "ISFJ", "ESFP",
            "INTJ", "ESFJ", "ESTP", "INFJ", "ENFP", "ISTJ"
        }
        if v.upper() not in valid_types:
            raise ValueError(f"Invalid MBTI type. Must be one of: {', '.join(valid_types)}")
        return v.upper()


class AgentState(BaseModel):
    """Serializable state of an agent."""
    id: str
    mbti_type: str
    iq_level: IQLevel
    word: Optional[str]
    role: AgentRole
    name: Optional[str] = None
    is_alive: bool = True
    is_possessed: bool = False
    suspicion_scores: Dict[str, int] = Field(default_factory=dict)
    vote_history: list = Field(default_factory=list)
    created_at: str


class Agent:
    """
    Game agent using CrewAI.

    This is the main agent class that integrates:
    - CrewAI for agent runtime
    - Configuration (MBTI, IQ, word)
    - Memory system (with corruption and dependencies)
    """
    
    def __init__(
        self,
        config: AgentConfig,
        memory_system: AgentMemorySystem,
        model_config: Optional[Dict[str, Any]] = None,
        llm_service: Optional["LLMService"] = None,
        runtime_context: Optional[str] = None,
    ):
        self.config = config
        self.memory_system = memory_system
        self.model_config = model_config  # 保存自定义模型配置
        self.runtime_context = runtime_context
        if llm_service is None:
            from services.llm_service import LLMService

            llm_service = LLMService()
        self.llm_service = llm_service
        
        self.is_alive = True
        self.is_possessed = False
        self.suspicion_scores: Dict[str, int] = {}
        self.vote_history: list = []
        self.created_at = datetime.now()
        
        # Create CrewAI agent runtime when the package is available.
        self._agent_runtime = self._create_crewai_agent()
        
        if self._agent_runtime is None:
            logger.warning(
                "CrewAI runtime not available for %s; continuing with LiteLLM-only flow.",
                self.config.id,
            )
    
    def _resolve_runtime_model_config(self) -> tuple[str, str, str, Optional[str]]:
        """Resolve provider, model name, API key, and base URL for the agent runtime."""
        if self.model_config:
            provider = (self.model_config.get("provider") or "openai").lower()
            model_name = self.model_config.get("model") or "gpt-4o-mini"
            api_key = self.model_config.get("api_key")
            base_url = self.model_config.get("base_url")

            if not base_url:
                if provider == "alibaba":
                    base_url = settings.ALIBABA_BASE_URL
                elif provider == "zhipu":
                    base_url = settings.ZHIPU_BASE_URL
                elif provider == "anthropic":
                    base_url = "https://api.anthropic.com/v1"
                elif provider == "ollama":
                    base_url = settings.OLLAMA_BASE_URL

            logger.info(
                "Using custom model config for %s: %s/%s",
                self.config.id,
                provider,
                model_name,
            )
            return provider, model_name, api_key or "test-key", base_url

        full_model = self._get_model_for_iq()
        provider, _, model_name = full_model.partition("/")
        if not model_name:
            provider = "openai"
            model_name = full_model
        api_key = self._get_api_key(full_model) or "test-key"
        base_url = self._get_base_url(full_model)
        return provider.lower(), model_name, api_key, base_url

    def _create_crewai_agent(self) -> Optional[Any]:
        """Create a CrewAI agent."""
        try:
            if CrewAIAgent is None or CrewAILLM is None:
                return None

            provider, model_name, api_key, base_url = self._resolve_runtime_model_config()
            llm_model = model_name if provider == "openai" else f"{provider}/{model_name}"

            logger.info("Creating CrewAI agent %s:", self.config.id)
            logger.info("  Model: %s", llm_model)
            logger.info("  Base URL: %s", base_url)
            logger.info("  API key present: %s, length: %s", bool(api_key), len(api_key or ""))

            llm = CrewAILLM(
                model=llm_model,
                api_key=api_key,
                base_url=base_url,
                temperature=0.8,
            )
            agent = CrewAIAgent(
                role=f"{self.config.name or self.config.id} game player",
                goal="Play the social deduction game while staying in character and producing strict JSON.",
                backstory=self._build_system_message(),
                llm=llm,
                verbose=False,
                allow_delegation=False,
            )

            logger.info("Created CrewAI agent: %s with model %s", self.config.id, llm_model)
            return agent
        except Exception as e:
            logger.error(f"Failed to create CrewAI agent for {self.config.id}: {e}")
            import traceback
            logger.error(traceback.format_exc())
            return None

    def _create_framework_agent(self) -> Optional[Any]:
        """Compatibility wrapper for older call sites."""
        return self._create_crewai_agent()
    
    def _get_model_for_iq(self) -> str:
        """Get full model name for agent's IQ level (with provider prefix)."""
        model_map = {
            IQLevel.HIGH: settings.MODEL_HIGH_IQ,
            IQLevel.MID: settings.MODEL_MID_IQ,
            IQLevel.LOW: settings.MODEL_LOW_IQ,
        }
        return model_map.get(self.config.iq_level, settings.MODEL_MID_IQ)
    
    def _get_model_name(self) -> str:
        """Get model name without provider prefix."""
        model = self._get_model_for_iq()
        if "/" in model:
            return model.split("/", 1)[1]
        return model

    def get_model_for_iq(self) -> str:
        """Compatibility wrapper for older orchestration code."""
        return self._get_model_for_iq()

    def _get_api_key(self, model: str) -> str:
        """Get API key for the model."""
        if "gpt" in model.lower() or "openai" in model.lower():
            return settings.OPENAI_API_KEY or ""
        elif "qwen" in model.lower() or "alibaba" in model.lower():
            return settings.ALIBABA_API_KEY or ""
        elif "glm" in model.lower() or "zhipu" in model.lower():
            return settings.ZHIPU_API_KEY or ""
        elif "claude" in model.lower() or "anthropic" in model.lower():
            return settings.ANTHROPIC_API_KEY or ""
        return ""

    def get_api_key_for_model(self, model: str) -> str:
        """Compatibility wrapper for older orchestration code."""
        return self._get_api_key(model)
    
    def _get_base_url(self, model: str) -> Optional[str]:
        """Get base URL for the model."""
        if "qwen" in model.lower() or "alibaba" in model.lower():
            return settings.ALIBABA_BASE_URL
        elif "glm" in model.lower() or "zhipu" in model.lower():
            return settings.ZHIPU_BASE_URL
        elif "ollama" in model.lower():
            return settings.OLLAMA_BASE_URL
        return None

    def get_base_url_for_model(self, model: str) -> Optional[str]:
        """Compatibility wrapper for older orchestration code."""
        return self._get_base_url(model)

    def needs_base_url(self, model: str) -> bool:
        """Compatibility wrapper for older orchestration code."""
        return self._get_base_url(model) is not None
    
    def _build_system_message(self) -> str:
        """Build system message with personality and game context."""
        from models.personality import PersonalityPrompt
        
        personality = PersonalityPrompt.get_default(self.config.mbti_type)
        
        system_msg = f"""# Role: 《谁是卧底》游戏参与者

## 你的身份:
- **ID**: {self.config.id}
- **MBTI**: {self.config.mbti_type}
- **IQ 等级**: {self.config.iq_level.value}
- **角色**: {self.config.role.value}
- **词**: {self.config.word if self.config.word else "未分配"}
{f'''
## 当前游戏上下文:
{self.runtime_context}
''' if self.runtime_context else ''}

## 性格特征:
{personality.traits}

## 说话风格:
{personality.speaking_style}

## 思维模式:
{personality.thinking_pattern}

## 游戏规则:
1. 不要直接说出你的词
2. 通过描述来暗示你的词
3. 观察其他玩家的描述，找出卧底
4. 保持你的性格特征和说话风格

## 输出格式 (CRITICAL - 必须严格遵守):

你的回复**必须**是有效的 JSON 格式，不要添加任何其他文字、解释或 markdown 标记。

### JSON Schema:
{{
  "thought": "string (max 500 characters) - 你的内心思考过程",
  "speech": "string (max 100 characters) - 你的公开描述（一句话）",
  "suspicion": {{
    "agent_id": integer (0-10) - 对其他 agent 的可疑度评分
  }}
}}

### 字段说明:
1. **thought**: 你的内心分析过程（最多500字）
   - 必须反映你的 MBTI 性格特征
   - 必须符合你的 IQ 等级思维模式
   - 不要直接透露你的词

2. **speech**: 你的公开描述（一句话，最多100字）
   - 必须是中文
   - 必须符合你的说话风格
   - 不要直接说出你的词
   - 根据 IQ 等级调整描述策略

3. **suspicion**: 对其他 agent 的可疑度评分（0-10）
   - 0 = 完全不怀疑
   - 10 = 高度怀疑
   - 必须基于逻辑推理
   - 可以为空对象 {{}}

### 示例输出:
{{
  "thought": "分析前两轮发言，Agent 2 的描述过于抽象，可能在隐藏关键特征。",
  "speech": "这个东西通常是白色的，早餐时很常见，营养价值很高。",
  "suspicion": {{"agent_2": 7, "agent_3": 3}}
}}

**重要**: 只输出 JSON，不要有任何其他内容！
"""
        return system_msg
    
    def _extract_json_from_text(
        self,
        text: str,
        *,
        required_fields: Optional[list[str]] = None,
    ) -> Optional[Dict[str, Any]]:
        """Try to extract JSON from text, handling incomplete responses."""
        original_text = text
        required_fields = required_fields or []
        
        # Try to find JSON in code blocks
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            if end != -1:
                text = text[start:end].strip()
            else:
                # Code block not closed, extract from start
                text = text[start:].strip()
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            if end != -1:
                text = text[start:end].strip()
            else:
                text = text[start:].strip()
        
        # Try to find JSON object
        start_idx = text.find("{")
        end_idx = text.rfind("}")
        
        if start_idx == -1:
            logger.warning(f"No opening brace found in response: {original_text[:200]}")
            return None
        
        if end_idx == -1 or end_idx < start_idx:
            # JSON might be incomplete, try to complete it
            logger.warning(f"Incomplete JSON detected, attempting to fix: {text[:200]}")
            text = text[start_idx:]
            # Try to close incomplete JSON
            if '"thought"' in text and '"speech"' not in text:
                # Very incomplete, can't fix
                return None
            # Try adding closing braces
            text = text.rstrip() + "}"
        else:
            text = text[start_idx:end_idx + 1]
        
        try:
            parsed = json.loads(text)
            for field in required_fields:
                if field not in parsed:
                    logger.warning("JSON missing '%s' field", field)
                    return None
            if required_fields:
                return parsed
            if "speech" not in parsed and "vote" not in parsed:
                logger.warning("JSON missing both 'speech' and 'vote' fields")
                return None
            return parsed
        except json.JSONDecodeError as e:
            logger.warning(f"JSON decode error: {e}, text: {text[:200]}")
            return None
    
    def _format_conversation_history_for_llm(self, conversation_history: list) -> list:
        """Convert conversation history to LiteLLM message format."""
        formatted_messages = []
        for msg in conversation_history:
            if not isinstance(msg, dict):
                continue
            if "role" in msg and "content" in msg:
                content = (msg["content"] or "").strip()
                if not content:
                    continue
                formatted_messages.append({"role": msg["role"], "content": content})
                continue
            content = (msg.get("content", "") or "").strip()
            if not content:
                continue
            agent_id = msg.get("agent_id", "Unknown")
            if agent_id == "system":
                role = "user"
                content = f"系统: {content}"
            else:
                role = "user"
                if content and not content.startswith(f"{agent_id}:"):
                    content = f"{agent_id}: {content}"
            formatted_messages.append({"role": role, "content": content})

        merged_messages = []
        for message in formatted_messages:
            if (
                merged_messages
                and merged_messages[-1]["role"] == message["role"]
                and message["role"] == "user"
            ):
                merged_messages[-1]["content"] = (
                    f"{merged_messages[-1]['content']}\n{message['content']}"
                )
            else:
                merged_messages.append(message)

        return merged_messages
    
    async def generate_description(
        self,
        system_prompt: str,
        conversation_history: list,
        current_round: int
    ) -> Dict[str, Any]:
        """
        Generate agent description.

        Args:
            system_prompt: System prompt with personality and rules
            conversation_history: Previous conversation
            current_round: Current game round

        Returns:
            Dict with thought, speech, and suspicion
        """
        if self.is_possessed:
            logger.warning(f"Agent {self.config.id} is possessed, cannot generate description")
            raise ValueError("Cannot generate description for possessed agent")

        # Apply memory decay
        self.memory_system.apply_memory_decay(current_round)

        # Get memory context
        memory_context = self.memory_system.get_conversation_context(current_round)

        # Build full prompt with memory context
        full_prompt = f"{system_prompt}\n\n## 你的记忆:\n{memory_context}"

        # Format conversation history for LiteLLM
        formatted_messages = self._format_conversation_history_for_llm(conversation_history)

        try:
            if self._agent_runtime is not None:
                framework_response = await self._run_crewai(
                    full_prompt,
                    formatted_messages,
                    temperature=0.8,
                    max_tokens=2200,
                    required_fields=["speech"],
                )
                response_data = framework_response
            else:
                response = await self.llm_service.generate_agent_response(
                    system_prompt=full_prompt,
                    conversation_history=formatted_messages,
                    iq_level=self.config.iq_level.value,
                    temperature=0.8,
                    model_config=self.model_config,
                )
                response_data = response.dict()
        except Exception as e:
            logger.error(f"Agent {self.config.id} failed to generate description: {e}")
            response_data = {
                "thought": "思考中...",
                "speech": "我需要更多时间思考。",
                "suspicion": {},
            }

        if "suspicion" in response_data:
            self.suspicion_scores.update(response_data.get("suspicion", {}))

        speech = response_data.get("speech") or "我需要更多时间思考。"
        response_data["speech"] = speech
        response_data.setdefault("thought", "思考中...")
        response_data.setdefault("suspicion", {})

        # Store in memory
        observation = f"我说: {speech}"
        self.memory_system.add_memory(observation, current_round)

        logger.info(f"Agent {self.config.id} generated description successfully")

        return response_data
    
    async def generate_vote(
        self,
        system_prompt: str,
        conversation_history: list,
        valid_agent_ids: list,
        current_round: int
    ) -> Dict[str, Any]:
        """
        Generate agent vote.

        Args:
            system_prompt: System prompt with voting instructions
            conversation_history: Previous conversation
            valid_agent_ids: List of agents that can be voted for
            current_round: Current game round

        Returns:
            Dict with thought, vote, and confidence
        """
        if self.is_possessed:
            logger.warning(f"Agent {self.config.id} is possessed, cannot generate vote")
            raise ValueError("Cannot generate vote for possessed agent")

        # Get memory context
        memory_context = self.memory_system.get_conversation_context(current_round)
        full_prompt = f"{system_prompt}\n\n## 你的记忆:\n{memory_context}"

        # Format conversation history for LiteLLM
        formatted_messages = self._format_conversation_history_for_llm(conversation_history)

        try:
            if self._agent_runtime is not None:
                framework_response = await self._run_crewai(
                    full_prompt,
                    formatted_messages,
                    temperature=0.7,
                    max_tokens=1200,
                    required_fields=["vote"],
                )
                response_data = framework_response
            else:
                response = await self.llm_service.generate_vote_response(
                    system_prompt=full_prompt,
                    conversation_history=formatted_messages,
                    iq_level=self.config.iq_level.value,
                    valid_agent_ids=valid_agent_ids,
                    temperature=0.7,
                    model_config=self.model_config,
                )
                response_data = response.dict()
            response_data["used_llm"] = True
        except Exception as e:
            logger.error(f"Agent {self.config.id} failed to generate vote: {e}")
            import random
            fallback_vote = random.choice(valid_agent_ids)
            response_data = {
                "thought": (
                    "模型投票生成失败；我根据当前公开信息不足的局面选择一个仍在场且可投的目标，"
                    "这次投票应视为系统保底而非完整推理。"
                ),
                "vote": fallback_vote,
                "confidence": 0.5,
                "used_llm": False,
            }

        vote_record = {
            "round": current_round,
            "voted_for": response_data["vote"],
            "confidence": response_data.get("confidence", 0.5),
        }
        self.vote_history.append(vote_record)

        vote_memory = f"我投票给 {response_data['vote']}，置信度: {response_data.get('confidence', 0.5)}"
        self.memory_system.add_memory(vote_memory, current_round)

        logger.info(f"Agent {self.config.id} generated vote successfully")

        return {
            "thought": response_data.get("thought", "投票中..."),
            "vote": response_data["vote"],
            "confidence": response_data.get("confidence", 0.5),
            "used_llm": response_data.get("used_llm", True),
        }
    
    def observe_event(self, event: str, round_number: int, dependencies: Optional[list] = None):
        """Record an observation in memory."""
        self.memory_system.add_memory(event, round_number, dependencies)
    
    def possess(self):
        """Mark agent as possessed by user."""
        self.is_possessed = True
    
    def release(self):
        """Release agent from user control."""
        self.is_possessed = False
    
    def eliminate(self):
        """Mark agent as eliminated from game."""
        self.is_alive = False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert agent to dictionary for serialization."""
        return {
            "id": self.config.id,
            "mbti_type": self.config.mbti_type,
            "iq_level": self.config.iq_level.value,
            "word": self.config.word,
            "role": self.config.role.value,
            "name": self.config.name,
            "model_config": self.model_config,
            "is_alive": self.is_alive,
            "is_possessed": self.is_possessed,
            "suspicion_scores": self.suspicion_scores,
            "vote_history": self.vote_history,
            "created_at": self.created_at.isoformat(),
            "memory_system": self.memory_system.to_dict()
        }

    @classmethod
    def from_dict(
        cls,
        data: Dict[str, Any],
        llm_service: Optional["LLMService"] = None,
    ) -> "Agent":
        """Rebuild an agent from serialized state."""
        config = AgentConfig(
            id=data["id"],
            mbti_type=data["mbti_type"],
            iq_level=IQLevel(data["iq_level"]),
            word=data.get("word"),
            role=AgentRole(data.get("role", AgentRole.CIVILIAN.value)),
            name=data.get("name"),
        )

        memory_system = AgentMemorySystem.from_dict(data["memory_system"])
        agent = cls(
            config=config,
            memory_system=memory_system,
            model_config=data.get("model_config"),
            llm_service=llm_service,
        )
        agent.is_alive = data.get("is_alive", True)
        agent.is_possessed = data.get("is_possessed", False)
        agent.suspicion_scores = data.get("suspicion_scores", {})
        agent.vote_history = data.get("vote_history", [])

        created_at = data.get("created_at")
        if created_at:
            agent.created_at = datetime.fromisoformat(created_at)

        return agent
    
    def get_state(self) -> AgentState:
        """Get serializable state."""
        return AgentState(
            id=self.config.id,
            mbti_type=self.config.mbti_type,
            iq_level=self.config.iq_level,
            word=self.config.word,
            role=self.config.role,
            name=self.config.name,
            is_alive=self.is_alive,
            is_possessed=self.is_possessed,
            suspicion_scores=self.suspicion_scores,
            vote_history=self.vote_history,
            created_at=self.created_at.isoformat()
        )
    
    async def _run_crewai(
        self,
        system_prompt: str,
        conversation_history: list[dict[str, str]],
        *,
        temperature: float,
        max_tokens: int,
        required_fields: Optional[list[str]] = None,
    ) -> Dict[str, Any]:
        """Run the CrewAI agent and parse JSON output."""
        if self._agent_runtime is None:
            raise RuntimeError("CrewAI runtime unavailable")

        prompt_parts = [system_prompt, "", "## 对话历史:"]
        if conversation_history:
            for item in conversation_history:
                prompt_parts.append(f"[{item['role']}] {item['content']}")
        else:
            prompt_parts.append("（暂无）")
        prompt_parts.append("")
        prompt_parts.append("请只输出一个 JSON 对象。")
        result, console_output = await asyncio.to_thread(
            self._kickoff_quietly,
            "\n".join(prompt_parts),
        )
        if console_output:
            logger.debug("Suppressed CrewAI console output for %s: %s", self.config.id, console_output[:500])
        output = getattr(result, "raw", None) or getattr(result, "text", "") or str(result)
        parsed = self._extract_json_from_text(output, required_fields=required_fields)
        if not parsed:
            raise ValueError(f"CrewAI output is not valid JSON: {output[:300]}")

        speech = parsed.get("speech")
        if isinstance(speech, str) and len(speech) > 220:
            parsed["speech"] = speech[:220]
        parsed.setdefault("thought", "思考中...")
        parsed.setdefault("suspicion", {})
        return parsed

    def _kickoff_quietly(self, prompt: str) -> tuple[Any, str]:
        """Run CrewAI while keeping its rich console output out of game logs."""
        stdout = io.StringIO()
        stderr = io.StringIO()
        with (
            self._suppress_crewai_lite_agent_console(),
            contextlib.redirect_stdout(stdout),
            contextlib.redirect_stderr(stderr),
        ):
            result = self._agent_runtime.kickoff(prompt)
        return result, stdout.getvalue() + stderr.getvalue()

    @contextlib.contextmanager
    def _suppress_crewai_lite_agent_console(self):
        """Temporarily detach CrewAI's LiteAgent Rich-panel event handlers."""
        try:
            from crewai.events import crewai_event_bus
            from crewai.events.types.agent_events import (
                LiteAgentExecutionCompletedEvent,
                LiteAgentExecutionErrorEvent,
                LiteAgentExecutionStartedEvent,
            )

            event_types = (
                LiteAgentExecutionStartedEvent,
                LiteAgentExecutionCompletedEvent,
                LiteAgentExecutionErrorEvent,
            )
            removed_handlers: list[tuple[Any, Any]] = []
            for event_type in event_types:
                handlers = list(crewai_event_bus._sync_handlers.get(event_type, ()))
                for handler in handlers:
                    if "on_lite_agent_execution_" in getattr(handler, "__name__", ""):
                        crewai_event_bus.off(event_type, handler)
                        removed_handlers.append((event_type, handler))
            try:
                yield
            finally:
                for event_type, handler in removed_handlers:
                    crewai_event_bus.on(event_type)(handler)
        except Exception:
            yield

    async def _run_framework(
        self,
        system_prompt: str,
        conversation_history: list[dict[str, str]],
        *,
        temperature: float,
        max_tokens: int,
        required_fields: Optional[list[str]] = None,
    ) -> Dict[str, Any]:
        """Compatibility wrapper for older call sites."""
        return await self._run_crewai(
            system_prompt,
            conversation_history,
            temperature=temperature,
            max_tokens=max_tokens,
            required_fields=required_fields,
        )
